name: Docker Image CI

on:
  push:
    branches: 
#       - master
      - dev
      - docker-action 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build --file Dockerfile --build-arg empireversion="$VERSION" -t vinnybod/empire:latest .
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
